export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHANGE_ITEM_AMOUNT = 'CHANGE_ITEM_AMOUNT';


export const USER_LOADING='USER_LOADING';
export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR='AUTH_ERROR';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL'
export const GET_ERRORS='GET_ERRORS';
export const CLEAR_ERRORS='CLEAR_ERRORS';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ORDER_START = 'ORDER_START';
export const ORDER_SUCCESS = 'ORDER_START';
export const ORDER_FAIL = 'ORDER_START';

